local set = vim.opt

set.number=true                          -- set numbered lines
set.relativenumber=true                  -- set relative numbered lines
set.wildmenu=true                        -- activates wildmenu
set.autowriteall=true                    -- saves buffers on buffer switch
set.cursorline=true                      -- highlight the current line
set.clipboard="unnamedplus"              -- allows neovim to access the system clipboard
set.backup=false                         -- creates a backup file
set.cmdheight=2                          -- more space in the neovim command line for displaying messages
set.completeopt={ "menu" , "menuone" , "noselect", "noinsert" } -- Let the user decide about the autocomplete
set.conceallevel=0                       -- so that `` is visible in markdown files
set.fileencoding="utf-8"                 -- the encoding written to a file
set.hlsearch=true                        -- highlight all matches on previous search pattern
set.ignorecase=true                      -- ignore case in search patterns
set.mouse="a"                            -- allow the mouse to be used in neovim
set.pumheight=10                         -- pop up menu height
set.showmatch=true                       -- Highlights the matching parenthesis
set.showmode=false                       -- we don't need to see things like -- INSERT -- anymore
set.showtabline=2                        -- always show tabs
set.smartcase=true                       -- smart case
set.splitbelow=true                      -- force all horizontal splits to go below current window
set.splitright=true                      -- force all vertical splits to go to the right of current window
set.swapfile=false                       -- creates a swapfile
set.termguicolors=true                   -- set term gui colors (most terminals support this)
set.timeoutlen=1500                      -- time to wait for a mapped sequence to complete (in milliseconds)
set.undofile=true                        -- enable persistent undo
set.updatetime=300                       -- faster completion (4000ms default)
set.writebackup=false                    -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
set.numberwidth=4                        -- set number column width to 2 {default 4}
set.signcolumn="yes"                     -- always show the sign column, otherwise it would shift the text each time
set.wrap=false                           -- display lines as one long line
set.scrolloff=8                          -- is one of my fav
set.sidescrolloff=8                      -- distance to start scrolling to the side automatically
set.guifont="monospace:h17"              -- the font used in graphical neovim applications
set.colorcolumn="80"                     -- sets lenght line
set.autoindent=true                      -- autoindents if possible
set.smartindent=true                     -- make indenting smarter again
set.tabstop=4                            -- insert 2 spaces for a tab
set.shiftwidth=4                         -- the number of spaces inserted for each indentation
set.softtabstop=4                        -- indentation of < and >
set.expandtab=true                       -- convert tabs to spaces

